name: regattalistner
version: git
summary: Command line regatta horn
description: |
  Start listner:-
    $ regattalistner

confinement: devmode
base: core18

parts:
  wethr:
    plugin: nodejs
    source: .

apps:
  wethr:
    command: regattalistner
